ASM_APPLICATION_DEV/Controllers/AccountsController.cs
using ASM_APPLICATION_DEV.Data;
using ASM_APPLICATION_DEV.Models;
using ASM_APPLICATION_DEV.Utils;
using ASM_APPLICATION_DEV.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace ASM_APPLICATION_DEV.Controllers
{
    public class AccountsController : Controller
    {
        private ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public AccountsController(ApplicationDbContext context, 
                                UserManager<User> userManager, 
                                RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
        }


        [HttpGet]
        public async Task<IActionResult> Index(string name)
        {

            if(name == "AllUser" || name == null)
            {
             var model = new AdminViewModel();

            foreach (var user in _userManager.Users)
            {
                if (!await _userManager.IsInRoleAsync(user, Role.ADMIN))
                {
                    model.Users.Add(user);
                }
            }

            return View(model);
            }

            else
            {
                var model = new AdminViewModel();

                foreach (var user in _userManager.Users)
                {
                    if (await _userManager.IsInRoleAsync(user, name))
                    {
                        model.Users.Add(user);
                    }
                }

                return View(model);
            }
        }

        [HttpGet]
        public IActionResult ChangePassword(string id)
        {
            var getUser = _context.Users.SingleOrDefault(t => t.Id == id);
            if (getUser == null || getUser.EmailConfirmed == false)
            {
                TempData["Message"] = "Can not update Because Email not confirmed";
                
                return View(getUser);
            }

            return View(getUser);
        }

        [HttpPost]
        public IActionResult ChangePassword(string id, [Bind("PasswordHash")] User user)
        {
            var getUser = _context.Users.SingleOrDefault(t => t.Id == id);
            var newPassword = user.PasswordHash; 

            if (getUser == null && getUser.EmailConfirmed == false)
            {
                return BadRequest();
            }
            if(newPassword == null)
            {
                ModelState.AddModelError("NoInput", "You have not input new password.");
                return View(getUser);
            }
          
            getUser.PasswordHash = _userManager.PasswordHasher.HashPassword(getUser, newPassword);
            TempData["Message"] = "Update Successfully";
            


            _context.SaveChanges();
            return RedirectToAction("Index");
        }



    }
}

ASM_APPLICATION_DEV/Controllers/BooksController.cs
using ASM_APPLICATION_DEV.Data;
using ASM_APPLICATION_DEV.DTOs.Responses;
using ASM_APPLICATION_DEV.Models;
using ASM_APPLICATION_DEV.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace ASM_APPLICATION_DEV.Controllers
{
	public class BooksController : Controller
	{
			private ApplicationDbContext _context;
			public BooksController(ApplicationDbContext context)
			{
				_context = context;
			}

			[HttpGet]
			public async Task<IActionResult> ViewAllBook(string searchString)
			{
				var books = await _context.Books.ToListAsync();
				if (!String.IsNullOrEmpty(searchString))
				{
					var searchBooks = await _context.Books.Where(s => s.NameBook!.Contains(searchString)).ToListAsync();
					return View(searchBooks);

				}
				return View(books);
			}

			[HttpGet]
			public async Task<IActionResult> Create()
			{
				var viewModel = new BookViewModel()
				{
					Categories = await _context.Categories
						.Where(c => c.Status == Enums.CategoryStatus.Accepted)
						.ToListAsync()
				};
				return View(viewModel);
			}

			[HttpPost]
			public async Task<IActionResult> Create(BookViewModel viewModel)
			{

				using (var memoryStream = new MemoryStream())
				{
					await viewModel.FormFile.CopyToAsync(memoryStream);

					var newBook = new Book
					{
						NameBook = viewModel.Book.NameBook,
						QuantityBook = viewModel.Book.QuantityBook,
						Price = viewModel.Book.Price,
						Author = viewModel.Book.Author,
						InformationBook = viewModel.Book.InformationBook,
						Image = memoryStream.ToArray(),
						CategoryId = viewModel.Book.CategoryId
					};
					_context.Books.Add(newBook);
					await _context.SaveChangesAsync();
				}
				return RedirectToAction("ViewAllBook");
			}


			[HttpGet]
			public async Task<IActionResult> Delete(int id)
			{
				var bookInDb = await _context.Books.SingleOrDefaultAsync(t => t.Id == id);
				if (bookInDb is null)
				{
					return NotFound();
				}
				_context.Books.Remove(bookInDb);
				_context.SaveChanges();

				return RedirectToAction("ViewAllBook");
			}

			[HttpGet]
			public IActionResult Edit(int id)
			{
				var bookInDb = _context.Books.SingleOrDefault(t => t.Id == id);
				if (bookInDb is null)
				{
					return NotFound();
				}

				var viewModel = new BookViewModel
				{
					Book = bookInDb,
					Categories = _context.Categories
						.Where(c => c.Status == Enums.CategoryStatus.Accepted)
						.ToList()
				};
				return View(viewModel);
			}

			[HttpPost]
			public IActionResult Edit(BookViewModel viewModel)
			{
				var bookInDb = _context.Books.SingleOrDefault(t => t.Id == viewModel.Book.Id);
				if (bookInDb is null)
				{
					return BadRequest();
				}


				bookInDb.NameBook = viewModel.Book.NameBook;
				bookInDb.QuantityBook = viewModel.Book.QuantityBook;
				bookInDb.Price = viewModel.Book.Price;
				bookInDb.InformationBook = viewModel.Book.InformationBook;
				bookInDb.CategoryId = viewModel.Book.CategoryId;

				_context.SaveChanges();

				return RedirectToAction("ViewAllBook");
			}

			[HttpGet]
			public IActionResult Details(int id)
			{
				var bookInDb = _context.Books
						.Include(t => t.Category)
						.SingleOrDefault(t => t.Id == id);
				if (bookInDb is null)
				{
					return NotFound();
				}
				string imageBase64Data = Convert.ToBase64String(bookInDb.Image);
				string image = string.Format("data:image/jpg;base64, {0}", imageBase64Data);
				ViewBag.Image = image;

				return View(bookInDb);
			}

        [HttpGet]
        public IActionResult ViewBooksForCustomer(string nameOrCategoryBook)

        {
            List<BookView> listBookInHome = new List<BookView>();
            var booksToBuy = _context.Books.Include(t => t.Category).ToList();

            if (!String.IsNullOrEmpty(nameOrCategoryBook))
            {
                booksToBuy = booksToBuy.Where(t => t.Category.NameCategory.ToLower().Contains(nameOrCategoryBook.ToLower())
                || t.NameBook.ToLower().Contains(nameOrCategoryBook.ToLower())).ToList();
            }
            foreach (var item in booksToBuy)
            {
                BookView book = new BookView();
                book.Id = item.Id;
                book.NameBook = item.NameBook;
                book.QuantityBook = item.QuantityBook;
                book.PriceBook = item.Price;
                book.ImageBook = ConvertByteArrayToStringBase64(item.Image);
				book.Author = item.Author;
                listBookInHome.Add(book);
            }
            return View(listBookInHome);
        }

        [NonAction]
        private string ConvertByteArrayToStringBase64(byte[] imageArray)
        {
            string imageBase64Data = Convert.ToBase64String(imageArray);

            return string.Format("data:image/jpg;base64, {0}", imageBase64Data);
        }

        [HttpGet]
        public IActionResult DetailsBookForCustomer(int id)
        {
            var book = _context.Books.SingleOrDefault(x => x.Id == id);
            BookView bookView = new BookView();
            bookView.Id = book.Id;
            bookView.NameBook = book.NameBook;
            bookView.QuantityBook = book.QuantityBook;
            bookView.PriceBook = book.Price;
            bookView.DescriptionBook = book.InformationBook;
            bookView.ImageBook = ConvertByteArrayToStringBase64(book.Image);
			bookView.Author = book.Author;	

            return View(bookView);
        }
    }
}

ASM_APPLICATION_DEV/Controllers/CategoriesController.cs
using ASM_APPLICATION_DEV.Data;
using ASM_APPLICATION_DEV.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASM_APPLICATION_DEV.Controllers
{
    public class CategoriesController : Controller
    {
        private ApplicationDbContext _context;
        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            IEnumerable<Category> categories = _context.Categories.ToList();
            return View(categories);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            var newCategory = new Category
            {
                NameCategory = category.NameCategory,
                Status = Enums.CategoryStatus.InProgess
            };

            _context.Add(newCategory);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult ManageCategory()
        {
            var categories = _context.Categories
                .Where(t => t.Status == Enums.CategoryStatus.InProgess)
                .ToList();

            return View("ManageCategory", categories);
        }

        [HttpGet]
        public IActionResult AcceptCategory(int id)
        {
            var categoryVerify = _context.Categories.SingleOrDefault(c => c.Id == id);

            if (categoryVerify == null)
            {
                return BadRequest();
            }

            categoryVerify.Status = Enums.CategoryStatus.Accepted;
            _context.SaveChanges();

            return RedirectToAction("ManageCategory");
        }

        [HttpGet]
        public IActionResult RejectCategory(int id)
        {
            var categoryVerify = _context.Categories.SingleOrDefault(c => c.Id == id);

            if (categoryVerify == null)
            {
                return BadRequest();
            }

            categoryVerify.Status = Enums.CategoryStatus.Rejected;
            _context.SaveChanges();

            return RedirectToAction("ManageCategory");
        }
    }
}

ASM_APPLICATION_DEV/Controllers/OrderDetailsController.cs
using ASM_APPLICATION_DEV.Data;
using ASM_APPLICATION_DEV.Models;
using ASM_APPLICATION_DEV.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace ASM_APPLICATION_DEV.Controllers
{
	[Authorize]
	public class OrderDetailsController : Controller
	{
		private ApplicationDbContext context;
		private readonly UserManager<User> userManager;

		public OrderDetailsController(ApplicationDbContext context, UserManager<User> userManager)
		{
			this.context = context;
			this.userManager = userManager;
		}

		[HttpGet]
		public IActionResult Index(int id)
		{
			Cart cart = new Cart();		
			int result = 0;

			if (id != 0)
			{
				cart.orderDetails = context.OrderDetails.Include(t => t.Order)
					.Include(t => t.Book).Where(t => t.OrderId == id).ToList();
				foreach (var item in cart.orderDetails)
				{
					result += item.Price;
				}
				cart.totalPrice = result;

				return View(cart);
			}
			cart.orderDetails = context.OrderDetails.Include(t => t.Book).Include(t => t.Order)
				.Where(t => t.Order.StatusOrder == Enums.OrderStatus.Unconfirmed 
				&& t.Order.UserId == userManager.GetUserId(User)).ToList();
			foreach(var item in cart.orderDetails)
			{
				result += item.Price;
			}
			cart.totalPrice =  result;

			return View(cart);
		}

		[HttpGet]
		public IActionResult Delete (int id)
		{
			var orderDetail = context.OrderDetails.Include(t => t.Order).SingleOrDefault(t => t.Id == id);
			orderDetail.Order.PriceOrder = 0;
			context.Remove(orderDetail);
			List<OrderDetail> orderDetails = context.OrderDetails.Include(t => t.Order).Where(t => t.OrderId == orderDetail.OrderId).ToList();

			foreach (var item in orderDetails)
			{			
				item.Order.PriceOrder += item.Price;
			}
			context.SaveChanges();

			return RedirectToAction("Index");
		}


		[HttpPost]
		public IActionResult Edit (Cart cart)
		{
			foreach (var item in cart.orderDetails)
			{
				var a = context.OrderDetails.SingleOrDefault(t => t.Id == item.Id);
			
					a.Quantity = item.Quantity;

	
			}
			context.SaveChanges();
			return RedirectToAction("Checkout", "Orders");
		}

        public IActionResult DetailsForStoreOwner(int id)
        {
            CheckOut checkOut = new CheckOut();

            var ordersDetails = context.OrderDetails
           .Include(t => t.Order).Include(t => t.Order.User).Include(t => t.Book)
           .Where(t => t.OrderId == id).ToList();


            checkOut.orderDetails = ordersDetails;
            checkOut.Name = ordersDetails[0].Order.User.FullName;
            checkOut.Address = ordersDetails[0].Order.User.Address;
            checkOut.TotalPrice = ordersDetails[0].Order.PriceOrder;

            return View(checkOut);
        }
    }
}

ASM_APPLICATION_DEV/Views/Shared/_Layout.cshtml
@using ASM_APPLICATION_DEV.Utils;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASM_APPLICATION_DEV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASM_APPLICATION_DEV.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASM_APPLICATION_DEV</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(Role.STORE_OWNER))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Books" asp-action="ViewAllBook">Book Management</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Categories" asp-action="Index">Category Management</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Orders" asp-action="ViewOrdersForStoreOwner">Record Management</a>
                            </li>

                        }
                        @if (User.IsInRole(Role.CUSTOMER))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Views" asp-controller="Books" asp-action="ViewBooksForCustomer">View Book</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="OrderDetails" asp-action="Index">Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Views" asp-controller="Home" asp-action="Help">Help</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Views" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
                            

                        }
                        @if (User.IsInRole(Role.STORE_OWNER))
                        {
                            <li class="nav-item">
                            </li>
                        }
                        @if (User.IsInRole(Role.ADMIN))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Views" asp-controller="Categories" asp-action="ManageCategory">Manage Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Views" asp-controller="Accounts" asp-action="Index">Manage Account</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASM_APPLICATION_DEV - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>